Add motorBench v2.55. Select MCLV-48V-300W board with dsPIC33CK256MP508. Select Linix 45ZWN24-40 motor. Generate code. Attempt build. main.c does not have MCAF functions. Build fails for undefined reference to MCC_OPA_x_Enable.